# Generated by Django 5.1.4 on 2025-01-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_profile',
            name='password',
            field=models.TextField(default='0'),
        ),
    ]
