# Generated by Django 5.1.4 on 2025-01-10 15:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accept_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('disease_diagnosed', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
                ('message_to_doctor', models.TextField()),
                ('doctor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('disease_diagnosed', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
                ('message_to_doctor', models.TextField()),
                ('doctor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Decline_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('disease_diagnosed', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
                ('message_to_doctor', models.TextField()),
                ('doctor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='uploads')),
                ('docter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('DateOfBirth', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('Designation', models.TextField(blank=True, max_length=200, null=True)),
                ('experience', models.IntegerField(blank=True, default=0, null=True)),
                ('NoOfCasesattended', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='refcases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date', models.CharField(default=datetime.date.today, max_length=200)),
                ('disease_diagnosed', models.CharField(blank=True, max_length=255, null=True)),
                ('case_details', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('doctor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('password', models.TextField(default='0')),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('contact', models.IntegerField(blank=True, default=0, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date', models.CharField(default=datetime.date.today, max_length=200)),
                ('disease_diagnosed', models.CharField(blank=True, max_length=255, null=True)),
                ('case_details', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('Appointment_confirmation', models.CharField(blank=True, default='0', max_length=2, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
