# Generated by Django 5.1.4 on 2024-12-18 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_visit',
        ),
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
