# Generated by Django 5.1.4 on 2024-12-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_patient_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='refcases',
            name='doctor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
