# Generated by Django 5.1.4 on 2024-12-25 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_refcases_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='uploads')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('DateOfBirth', models.DateField(default=datetime.date.today)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=200)),
                ('Designation', models.TextField(max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('NoOfCasesattended', models.IntegerField()),
            ],
        ),
    ]
