# Generated by Django 5.1.4 on 2024-12-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_patient_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='docter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
