# Generated by Django 5.1.4 on 2024-12-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_profile_docter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refcases',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcases',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcases',
            name='case_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcases',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcases',
            name='disease_diagnosed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='refcases',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
