# Generated by Django 5.1.4 on 2024-12-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_patient_age_alter_patient_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('disease_diagnosed', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=200)),
                ('time', models.TimeField(max_length=200)),
                ('message_to_doctor', models.TextField()),
                ('doctor', models.CharField(max_length=10)),
            ],
        ),
    ]
