# Generated by Django 5.1.4 on 2024-12-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('disease_diagnosed', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
                ('message_to_doctor', models.TextField()),
                ('doctor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Decline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('disease_diagnosed', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
                ('message_to_doctor', models.TextField()),
                ('doctor', models.CharField(max_length=10)),
            ],
        ),
    ]
