# Generated by Django 5.1.4 on 2024-12-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_acceptmodel_delete_accept_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcceptModel',
            new_name='Accept_Model',
        ),
    ]
