# Generated by Django 5.1.4 on 2024-12-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_rename_acceptmodel_accept_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Appointment_confirmation',
            field=models.CharField(blank=True, default='0', max_length=2, null=True),
        ),
    ]
